image: registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-alpine
stages:
  - build
  - test

variables:
  THREADS: 9
  GIT_SUBMODULE_STRATEGY: recursive

rank-lips-static:
  stage: build
  before_script:
    - ghc --version
  script:
    - sudo apk add xz xz-dev icu icu-dev icu-static zlib-static
    - cabal update
    - |
      cabal --store-dir=$(pwd)/.cabal-store \
        v2-install \
        --disable-shared --enable-static --enable-executable-static \
        -fstatic --ghc-options='-optl=-static' \
        --installdir=out --overwrite-policy=always \
        exe:rank-lips
    - ls -lhL out/    
    - rm -Rf result; mkdir -p result; cp -L out/rank-lips result/
  cache:
    paths:
      - .cabal-store
  artifacts:
    expire_in: 3 days
    paths:
      - result


cmd-parameter-test:
  stage: test
  dependencies:
    - rank-lips-static
  script:
    - sudo apk add jq
    - |
      export bin=$(pwd)/result
      cd rank-lips-example
      ./run.sh
      rm -R out

backwards-compatibility-V10-test:
  stage: test
  dependencies:
    - rank-lips-static
  script:
    - |
      export bin=$(pwd)/result
      cd eal-experiment
      ./run-eal.sh
      rm -R out      

jsonl-cmd-parameter-test:
  stage: test
  dependencies:
    - rank-lips-static
  script:
    - sudo apk add jq
    - |
      export bin=$(pwd)/result
      cd rank-lips-jsonl-example
      ./run-jsonl.sh
      rm -R out





ent-rank-lips-static:
  stage: build
  before_script:
    - ghc --version
  script:
    - sudo apk add xz xz-dev icu icu-dev icu-static zlib-static
    - cabal update
    - |
      cabal --store-dir=$(pwd)/.cabal-store \
        v2-install \
        --disable-shared --enable-static --enable-executable-static \
        -fstatic --ghc-options='-optl=-static' \
        --installdir=out --overwrite-policy=always \
        exe:rank-lips
    - ls -lhL out/    
    - rm -Rf result; cp -Lr out/ent-rank-lips result
  cache:
    paths:
      - .cabal-store
  artifacts:
    expire_in: 3 days
    paths:
      - result      