variables:
  THREADS: 9
  GIT_SUBMODULE_STRATEGY: recursive

static-dist:
  image: registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-alpine
  before_script:
    - ghc --version
  script:
    - sudo apk add xz xz-dev icu icu-dev icu-static zlib-static
    - cabal update
    - |
      cabal --store-dir=$(pwd)/.cabal-store \
        v2-install \
        --disable-shared --enable-static --enable-executable-static \
        -fstatic --ghc-options='-optl=-static' \
        --installdir=out --overwrite-policy=always \
        exe:rank-lips
    - rm -Rf result; cp -Lr out/ result
  cache:
    paths:
      - .cabal-store
  artifacts:
    expire_in: 8 weeks
    paths:
      - result
